In [1]:
from neural_bow_classifier import NeuralBOW0
import torch
import torch.nn as nn
import torch.nn.functional as F
import inspect

In [2]:
model = NeuralBOW0(setup=dict())

In [3]:
lookup_tensor = torch.tensor([[1,2,3],[10,11,12]])
lookup_tensor

tensor([[ 1,  2,  3],
        [10, 11, 12]])

In [4]:
embds = model.embeddings(lookup_tensor)
embds.shape

torch.Size([2, 3, 100])

In [6]:
model(lookup_tensor)

tensor([[-0.8417, -0.5639],
        [-0.7174, -0.6695]], grad_fn=<LogSoftmaxBackward>)

###### 

In [9]:
m = nn.Sigmoid()
loss = nn.BCELoss()
the_input = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)
output = loss(m(the_input), target)
output.backward()

In [11]:
output


tensor(0.9990, grad_fn=<BinaryCrossEntropyBackward>)

In [26]:
the_input.gt(0.5).float()

tensor([0., 0., 0.])

In [28]:
the_input.div(3)

tensor([-0.1823, -0.4156, -0.2018], grad_fn=<DivBackward0>)